# OctoFHIR Server Configuration Template

[server]
port = 8080
host = "0.0.0.0"
base_url = "http://localhost:8080"

[cors]
allowed_origins = ["*"]

[storage.in_memory]
preallocate = false

[search]
default_count = 10
max_count = 100

[packages]
load = ["hl7.fhir.r4b.core#4.3.0", "hl7.terminology#5.5.0"]

[otel]
enabled = true
service_name = "octofhir-server"
environment = "dev"
otlp_endpoint = "http://localhost:4318"

[logging]
level = "info"

[reload]
watch = true
debounce_ms = 200