pub mod admin;
pub mod bootstrap;
pub mod canonical;
pub mod config;
pub mod config_watch;
pub mod gateway;
pub mod handlers;
pub mod mapping;
pub mod middleware;
pub mod observability;
pub mod operations;
pub mod patch;
pub mod server;
pub mod storage_adapter;
pub mod validation;

pub use admin::{admin_routes, AdminState, CombinedAdminState};
pub use config::{AppConfig, OtelConfig, PostgresStorageConfig, ServerConfig};
pub use observability::{init_tracing, shutdown_tracing};
pub use server::{AppState, OctofhirServer, ServerBuilder, build_app};
