import { palette } from "./colors";

export const tokens = {
    brand: {
        primary: palette.primary[5],
        primaryHover: palette.primary[6],
        primaryActive: palette.primary[7],
        primarySoft: palette.primary[0],
        primaryRing: palette.primary[2],
        accent: palette.accent[5],
        accentHover: palette.accent[6],
        accentSoft: palette.accent[0],
        info: palette.info[5],
        infoHover: palette.info[6],
        infoSoft: palette.info[0],
        success: palette.success[5],
        successHover: palette.success[6],
        successSoft: palette.success[0],
        fire: palette.error[5],
        fireHover: palette.error[6],
        fireActive: palette.error[7],
        fireSoft: palette.error[0],
        warm: palette.warning[5],
        warmHover: palette.warning[6],
        warmSoft: palette.warning[0],
        deep: palette.deep[8],
        gradient: `linear-gradient(132deg, ${palette.primary[5]} 0%, ${palette.accent[5]} 100%)`,
        gradientSoft: `linear-gradient(145deg, ${palette.primary[1]} 0%, ${palette.accent[1]} 100%)`,
    },
    scheme: {
        light: {
            surface: {
                1: palette.gray[0],
                2: palette.gray[1],
                3: palette.gray[2],
                4: palette.gray[3],
            },
            text: {
                primary: palette.gray[9],
                secondary: palette.gray[6],
                muted: palette.gray[5],
                inverse: "#ffffff",
            },
            border: {
                subtle: palette.gray[2],
                strong: palette.gray[3],
            },
            accent: {
                primary: palette.primary[5],
                primaryHover: palette.primary[4],
                primaryActive: palette.primary[6],
                primaryGradientFrom: palette.primary[4],
                primaryGradientTo: palette.primary[5],
                fire: palette.error[5],
                fireHover: palette.error[4],
                fireActive: palette.error[6],
                fireGradientFrom: palette.error[4],
                fireGradientTo: palette.error[5],
                warm: palette.warning[5],
                primaryBg: palette.primary[0],
                primaryBgHover: palette.primary[1],
                fireBg: palette.error[0],
                fireBgHover: palette.error[1],
                warmBg: palette.warning[0],
            },
            focus: {
                ring: palette.primary[2],
            },
            effect: {
                buttonInsetTop: "inset 0 1px 0 oklch(100% 0 0 / 0.26)",
                buttonInsetBottom: "inset 0 -1px 0 oklch(0% 0 0 / 0.12)",
                buttonPressed: "inset 0 2px 3px oklch(0% 0 0 / 0.15)",
                surfaceInset: "inset 0 1px 0 oklch(100% 0 0 / 0.35), inset 0 -1px 0 oklch(0% 0 0 / 0.04)",
                elevated: "0 4px 10px oklch(30% 0.04 255 / 0.08)",
            },
            identity: {
                glowPrimary: "oklch(95% 0.05 255 / 0.3)",
                glowFire: "oklch(91% 0.06 25 / 0.1)",
                glowWarm: "oklch(95% 0.05 75 / 0.16)",
                baseTop: palette.gray[0],
                baseBottom: palette.gray[1],
                grid: "oklch(72% 0.02 255 / 0.08)",
                panel: "oklch(100% 0 0 / 0.95)",
            },
        },
        dark: {
            surface: {
                1: "#06121a",
                2: "#0b1a24",
                3: "#132634",
                4: "#1b3243",
            },
            text: {
                primary: "#f8f9fe",
                secondary: palette.gray[3],
                muted: palette.gray[5],
                inverse: "#0d0e1a",
            },
            border: {
                subtle: "#1f3a4d",
                strong: "#2b5068",
            },
            accent: {
                primary: palette.primary[4],
                primaryHover: palette.primary[3],
                primaryActive: palette.primary[5],
                primaryGradientFrom: palette.primary[3],
                primaryGradientTo: palette.primary[4],
                fire: palette.error[4],
                fireHover: palette.error[3],
                fireActive: palette.error[5],
                fireGradientFrom: palette.error[3],
                fireGradientTo: palette.error[4],
                warm: palette.warning[4],
                primaryBg: "#123040",
                primaryBgHover: "#1b4358",
                fireBg: "#3b251d",
                fireBgHover: "#4e3126",
                warmBg: "#2b341d",
            },
            focus: {
                ring: palette.primary[4],
            },
            effect: {
                buttonInsetTop: "inset 0 1px 0 oklch(100% 0 0 / 0.14)",
                buttonInsetBottom: "inset 0 -1px 0 oklch(0% 0 0 / 0.35)",
                buttonPressed: "inset 0 2px 4px oklch(0% 0 0 / 0.5)",
                surfaceInset: "inset 0 1px 0 oklch(100% 0 0 / 0.08), inset 0 -1px 0 oklch(0% 0 0 / 0.35)",
                elevated: "0 8px 18px oklch(0% 0 0 / 0.35)",
            },
            identity: {
                glowPrimary: "oklch(46% 0.1 255 / 0.26)",
                glowFire: "oklch(45% 0.11 25 / 0.15)",
                glowWarm: "oklch(48% 0.08 75 / 0.18)",
                baseTop: "#040c12",
                baseBottom: "#09151e",
                grid: "oklch(76% 0.035 255 / 0.08)",
                panel: "oklch(18% 0.022 255 / 0.84)",
            },
        },
    },
    typography: {
        family: '"Manrope", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        heading: '"Rubik", "Manrope", sans-serif',
        mono: '"JetBrains Mono", "SF Mono", "Fira Code", Consolas, monospace',
        weight: {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
        },
        size: {
            xs: "0.75rem",
            sm: "0.875rem",
            md: "1rem",
            lg: "1.125rem",
            xl: "1.25rem",
        },
        lineHeight: {
            tight: 1.2,
            normal: 1.5,
            relaxed: 1.65,
        },
        letterSpacing: {
            tight: "-0.01em",
            normal: "0",
        },
    },
    spacing: {
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1.25rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "4rem",
    },
    radius: {
        xs: "3px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        pill: "9999px",
    },
    shadow: {
        xs: "0 1px 0 oklch(0% 0 0 / 0.06)",
        sm: "0 1px 2px oklch(0% 0 0 / 0.08)",
        md: "0 4px 12px oklch(0% 0 0 / 0.1)",
        lg: "0 10px 24px oklch(0% 0 0 / 0.12)",
        xl: "0 16px 32px oklch(0% 0 0 / 0.16)",
    },
    motion: {
        fast: "100ms",
        normal: "150ms",
        slow: "200ms",
        ease: "cubic-bezier(0.4, 0, 0.2, 1)",
        easeOut: "cubic-bezier(0.16, 1, 0.3, 1)",
    },
    layout: {
        headerHeight: 48,
        sidebarWidth: 240,
        sidebarCollapsedWidth: 64,
        contentMaxWidth: 1400,
    },
} as const;

export type OctoTokens = typeof tokens;
