import { palette } from "./colors";

export const tokens = {
    brand: {
        primary: palette.primary[5],
        primaryHover: palette.primary[6],
        primaryActive: palette.primary[7],
        primarySoft: palette.primary[0],
        primaryRing: palette.primary[2],
        accent: palette.accent[5],
        accentHover: palette.accent[6],
        accentSoft: palette.accent[0],
        info: palette.info[5],
        infoHover: palette.info[6],
        infoSoft: palette.info[0],
        success: palette.success[5],
        successHover: palette.success[6],
        successSoft: palette.success[0],
        fire: palette.error[5],
        fireHover: palette.error[6],
        fireActive: palette.error[7],
        fireSoft: palette.error[0],
        warm: palette.warning[5],
        warmHover: palette.warning[6],
        warmSoft: palette.warning[0],
        deep: palette.deep[8],
        gradient: `linear-gradient(132deg, ${palette.primary[5]} 0%, ${palette.accent[5]} 100%)`,
        gradientSoft: `linear-gradient(145deg, ${palette.primary[1]} 0%, ${palette.accent[1]} 100%)`,
    },
    scheme: {
        light: {
            surface: {
                1: palette.gray[0],
                2: "oklch(98% 0.003 258)",
                3: "oklch(96% 0.005 258)",
                4: "oklch(93% 0.007 258)",
                hover: "oklch(96% 0.005 258)",
            },
            text: {
                primary: palette.gray[9],
                secondary: "oklch(48% 0.014 258)",
                muted: "oklch(58% 0.014 258)",
                inverse: "#ffffff",
            },
            border: {
                subtle: "oklch(91% 0.008 258)",
                strong: "oklch(85% 0.010 258)",
            },
            accent: {
                primary: palette.primary[5],
                primaryHover: palette.primary[4],
                primaryActive: palette.primary[6],
                primarySubtle: palette.primary[1],
                primaryGradientFrom: palette.primary[4],
                primaryGradientTo: palette.primary[5],
                fire: palette.error[5],
                fireHover: palette.error[4],
                fireActive: palette.error[6],
                fireGradientFrom: palette.error[4],
                fireGradientTo: palette.error[5],
                warm: palette.warning[5],
                positive: palette.success[5],
                info: palette.info[5],
                primaryBg: "oklch(96% 0.022 168)",
                primaryBgHover: palette.primary[1],
                fireBg: palette.error[0],
                fireBgHover: palette.error[1],
                warmBg: palette.warning[0],
                infoBg: palette.info[0],
            },
            focus: {
                ring: palette.primary[2],
            },
            effect: {
                buttonInsetTop: "inset 0 1px 0 oklch(100% 0 0 / 0.26)",
                buttonInsetBottom: "inset 0 -1px 0 oklch(0% 0 0 / 0.12)",
                buttonPressed: "inset 0 2px 3px oklch(0% 0 0 / 0.15)",
                surfaceInset: "inset 0 1px 0 oklch(100% 0 0 / 0.35), inset 0 -1px 0 oklch(0% 0 0 / 0.04)",
                elevated: "0 4px 10px oklch(30% 0.04 255 / 0.08)",
            },
            identity: {
                glowPrimary: "oklch(95% 0.05 255 / 0.3)",
                glowFire: "oklch(91% 0.06 25 / 0.1)",
                glowWarm: "oklch(95% 0.05 75 / 0.16)",
                baseTop: palette.gray[0],
                baseBottom: palette.gray[1],
                grid: "oklch(72% 0.02 255 / 0.08)",
                panel: "oklch(100% 0 0 / 0.95)",
            },
        },
        dark: {
            surface: {
                1: "#06121a",
                2: "#0a1721",
                3: "#0e1e29",
                4: "#142836",
                hover: "#0e1e29",
            },
            text: {
                primary: "#f8f9fe",
                secondary: palette.gray[3],
                muted: palette.gray[5],
                inverse: "#0d0e1a",
            },
            border: {
                subtle: "#1d3344",
                strong: "#2b5068",
            },
            accent: {
                primary: palette.primary[4],
                primaryHover: palette.primary[3],
                primaryActive: palette.primary[5],
                primarySubtle: "#0d2a24",
                primaryGradientFrom: palette.primary[3],
                primaryGradientTo: palette.primary[4],
                fire: palette.error[4],
                fireHover: palette.error[3],
                fireActive: palette.error[5],
                fireGradientFrom: palette.error[3],
                fireGradientTo: palette.error[4],
                warm: palette.warning[4],
                positive: palette.success[4],
                info: palette.info[4],
                primaryBg: "#0d2a24",
                primaryBgHover: "#114036",
                fireBg: "#3b251d",
                fireBgHover: "#4e3126",
                warmBg: "#2b341d",
                infoBg: "#102a3b",
            },
            focus: {
                ring: palette.primary[4],
            },
            effect: {
                buttonInsetTop: "inset 0 1px 0 oklch(100% 0 0 / 0.14)",
                buttonInsetBottom: "inset 0 -1px 0 oklch(0% 0 0 / 0.35)",
                buttonPressed: "inset 0 2px 4px oklch(0% 0 0 / 0.5)",
                surfaceInset: "inset 0 1px 0 oklch(100% 0 0 / 0.08), inset 0 -1px 0 oklch(0% 0 0 / 0.35)",
                elevated: "0 8px 18px oklch(0% 0 0 / 0.35)",
            },
            identity: {
                glowPrimary: "oklch(46% 0.1 255 / 0.26)",
                glowFire: "oklch(45% 0.11 25 / 0.15)",
                glowWarm: "oklch(48% 0.08 75 / 0.18)",
                baseTop: "#040c12",
                baseBottom: "#09151e",
                grid: "oklch(76% 0.035 255 / 0.08)",
                panel: "oklch(18% 0.022 255 / 0.84)",
            },
        },
    },
    typography: {
        family: '"Inter Variable", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        heading: '"Inter Variable", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        mono: '"JetBrains Mono", "SF Mono", "Fira Code", Consolas, monospace',
        weight: {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
        },
        size: {
            xs: "0.75rem",
            sm: "0.875rem",
            md: "0.9375rem",
            lg: "1.0625rem",
            xl: "1.1875rem",
        },
        lineHeight: {
            tight: 1.2,
            normal: 1.45,
            relaxed: 1.6,
        },
        letterSpacing: {
            tight: "-0.01em",
            normal: "0",
        },
    },
    spacing: {
        xs: "0.375rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
    },
    radius: {
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "10px",
        pill: "9999px",
    },
    shadow: {
        xs: "none",
        sm: "none",
        md: "0 2px 8px oklch(20% 0.03 258 / 0.10), 0 0 0 1px oklch(20% 0.03 258 / 0.06)",
        lg: "0 8px 24px oklch(20% 0.03 258 / 0.14), 0 0 0 1px oklch(20% 0.03 258 / 0.06)",
        xl: "0 8px 24px oklch(20% 0.03 258 / 0.14), 0 0 0 1px oklch(20% 0.03 258 / 0.06)",
    },
    motion: {
        fast: "100ms",
        normal: "150ms",
        slow: "200ms",
        ease: "cubic-bezier(0.4, 0, 0.2, 1)",
        easeOut: "cubic-bezier(0.16, 1, 0.3, 1)",
    },
    layout: {
        headerHeight: 48,
        sidebarWidth: 240,
        sidebarCollapsedWidth: 64,
        contentMaxWidth: 1400,
    },
} as const;

export type OctoTokens = typeof tokens;
